# -*- coding: utf-8 -*-
"""CodeUsed.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H82purBlb6aPR1o3jWQyTDzRkdUrWk-B
"""

import matplotlib.pyplot as plt
import pandas as pd
from collections import Counter
plt.style.use('fivethirtyeight')

df = pd.read_csv('/content/data.csv')
languages = df['LanguagesWorkedWith']

languages_counter = Counter()

for lan in languages:
    languages_counter.update(lan.split(';'))

x = []
y = []
for i in languages_counter.most_common(20):
    x.append(i[0])
    y.append(i[1])

x.reverse()
y.reverse()

plt.barh(x,y)
plt.title("Top Used Programming Languges All Over The World")
plt.xlabel("The Number Of People Who Uses Them")
plt.tight_layout()
plt.show()