# -*- coding: utf-8 -*-
"""CodeUsed.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H82purBlb6aPR1o3jWQyTDzRkdUrWk-B
"""

from matplotlib import pyplot as plt
plt.style.use("fivethirtyeight")

size = [59219, 55466, 47544, 36443, 35917]
labels = ['JavaScript', 'HTML/CSS', 'SQL', 'Python', 'Java']
explode = [0.1, 0, 0, 0, 0]

plt.pie(size,
        labels = labels,
        explode = explode,
        shadow = True,
        startangle = 90,
        autopct = '%1.1f%%',
        #radius=10,
        wedgeprops = {'edgecolor' : 'black'})


plt.title("My first pie chart")
plt.tight_layout()
plt.show()

